

services:
  postgres:
    image: postgres:10
    container_name: my_postgres_container2
    ports:
      - "3306:3306"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Iyanda
      POSTGRES_DB: tactology-global
    volumes:
      - my_postgres_data:/var/lib/postgresql/data


  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  my_postgres_data: